name: PDVzando
favicon: null
layout_spectrum: 0.34403008525259793
typography_spectrum: 0.9200885083992034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03721106261946261
  lightness: 0.9858600269071758
  saturation: 0.9777242376003414
  rhythmicContrast: 0.601905613206327
purpose: []
